apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
spec:
  replicas: 2
  selector:
    matchLabels:
      run: sample-api
  template:
    metadata:
      labels:
        run: sample-api
    spec:
      containers:
        - name: sample-api
          image: dacranesampleacr.azurecr.io/sample-api:v1
          ports:
            - containerPort: 3000
